Release 1.4
nf-core/pixelator pull request #121
Opened 2024-12-13 14:53 UTC by fbdtemme

## [[1.4.0](https://github.com/nf-core/pixelator/releases/tag/1.4.0)] - 2024-01-16

### Enhancements & fixes

- [[PR #111](https://github.com/nf-core/pixelator/pull/111)] - Template update for nf-core/tools v3.0.2
- [[PR #112](https://github.com/nf-core/pixelator/pull/112)] - Add graph refinement options for pixelator 0.19
- [[PR #113](https://github.com/nf-core/pixelator/pull/113)] - Fix validation issues after nf-core/tools v3.0.2 update
- [[PR #114](https://github.com/nf-core/pixelator/pull/114)] - Remove `--save_recovered_components` options for graph outputs
- [[PR #115](https://github.com/nf-core/pixelator/pull/115)] - Update containers for pixelator 0.19
- [[PR #116](https://github.com/nf-core/pixelator/pull/116)] - Bump version to 1.4
- [[PR #117](https://github.com/nf-core/pixelator/pull/117)] - Template update for nf-core/tools v3.1.0
- [[PR #118](https://github.com/nf-core/pixelator/pull/118)] - Update metromap, bump conda versions
- [[PR #120](https://github.com/nf-core/pixelator/pull/120)] - Add process_long to AMPLICON and COLLAPSE steps
- [[PR #122](https://github.com/nf-core/pixelator/pull/122)] - Template update for nf-core/tools v3.1.1
- [[PR #124](https://github.com/nf-core/pixelator/pull/124)] - Add manifest.contributors metadata to nextflow.config
- [[PR #125](https://github.com/nf-core/pixelator/pull/125)] - Use environment.yml files for all conda process directives
- [[PR #123](https://github.com/nf-core/pixelator/pull/123)] - Add nf-test tests for local modules and subworkflows

2024-12-19 13:17 UTC, ambarrio commented
Can you give us a hand on this one @mashehu and @avani-bhojwani on a short timeline? Thanks!

2024-12-21 02:46 UTC, avani-bhojwani commented
consider updating to version 2.0.0, rather than 1.4.0 since the deprecation of a parameter could justify a major release (https://nf-co.re/docs/guidelines/pipelines/requirements/semantic_versioning#major-release-eg-143-to-200)

2024-12-21 04:23 UTC, avani-bhojwani requested changes
Looks good - Just a few questions/changes

2025-01-03 10:58 UTC, fbdtemme commented on nextflow.config
>  }
Aha, I was not aware of that.
All parameters are already passed through closures in the config so we are not hit by any of the effects mentioned but reverted anyway to keep the sync with the template.

2025-01-03 10:59 UTC, fbdtemme commented on conf/pixelgen_aws.config
Yep, thanks.

2025-01-03 11:14 UTC, fbdtemme commented
Since the push to follow semantic versioning more strictly is only from last month, we would like to do this still as a minor release. We will have a v2 following quite soon and can start strict semantic versioning with that version.

2025-01-04 04:13 UTC, avani-bhojwani approved these changes

2025-01-04 05:23 UTC, sateeshperi reviewed
please see comments about local modules. Would also be great if they are unit tested with nf-tests. is this something you can work on adding before release ?

2025-01-04 05:23 UTC, sateeshperi commented on CHANGELOG.md
> +## [[1.4.0](https://github.com/nf-core/pixelator/releases/tag/1.4.0)] - 2024-12-13
update date before release

2025-01-04 05:23 UTC, sateeshperi commented on docs/output.md
> +- [Pipeline information](#pipeline-information) - Report metrics generated during the workflow execution
best to list these steps in the order of execution

2025-01-04 05:23 UTC, sateeshperi commented on docs/output.md
> +(see `--multiplet_recovery`). These new component IDs are then stored in the "component" column.
stored in column where ?

2025-01-04 05:23 UTC, sateeshperi commented on modules/local/pixelator/collect_metadata.nf
> +    conda "bioconda::pixelator=0.19.0"
best to follow the standard practice of putting the package info in an `environment.yml` and provide that

2025-01-04 05:23 UTC, sateeshperi commented on modules/local/pixelator/collect_metadata.nf
> +    def nextflowJson = groovy.json.JsonOutput.toJson(metadata)
need to collect version info from this module

2025-01-04 05:23 UTC, sateeshperi commented on nextflow.config
> +            name: 'Pixelgen Technologies AB',
update contributor info

2025-01-04 05:23 UTC, sateeshperi commented on nextflow.config
> -includeConfig 'conf/modules.config'
don't need modules.config ?

2025-01-09 13:58 UTC, fbdtemme commented on nextflow.config
> -includeConfig 'conf/modules.config'
This include was moved to the bottom of the file in the latest pipeline template: https://github.com/nf-core/pixelator/blob/ca529a0f889ef7b6f2d741e8f919d8c9e0834919/nextflow.config#L363C1-L363C36

2025-01-15 15:19 UTC, fbdtemme commented on modules/local/pixelator/collect_metadata.nf
> +    def nextflowJson = groovy.json.JsonOutput.toJson(metadata)
This is done here together with testing: https://github.com/nf-core/pixelator/pull/123

2025-01-15 15:20 UTC, fbdtemme commented on modules/local/pixelator/collect_metadata.nf
> +    conda "bioconda::pixelator=0.19.0"
Done in https://github.com/nf-core/pixelator/pull/125

2025-01-15 15:33 UTC, fbdtemme commented on docs/output.md
> +(see `--multiplet_recovery`). These new component IDs are then stored in the "component" column.
These new components are added inside the pixeldataset which consists in part of an embedded anndata object. I find the whole last sentence a bit confusing so I have just removed it. Extensive documentation on how to deal with the pipeline output files is provided in the [Pixelgen data analysis tutorials](https://software.pixelgen.com/mpx-analysis/latest/introduction/).

2025-01-15 15:34 UTC, fbdtemme commented on docs/output.md
> +- [Pipeline information](#pipeline-information) - Report metrics generated during the workflow execution
Fixed: [0b0b2ca](https://github.com/nf-core/pixelator/pull/121/commits/0b0b2caf5aa490841bd304cf1a43a0a85efbcdd5)

2025-01-16 12:21 UTC, fbdtemme commented
It took a while but all comments should but tests are added and all comments should be addressed now.
The remaining tests failures are because of a [nextflow bug](https://github.com/nextflow-io/nextflow/pull/5489) in the 24.04 series that has been fixed later. Can you recheck @sateeshperi ? Thanks!

2025-01-22 06:20 UTC, sateeshperi approved these changes

2025-01-22 11:34 UTC, merged